# HW 4

In [17]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Problem 1

**Note:** This is a repeat of a problem from HW 3 to try and make the difference between the two cases clearer.

Frames $A$ and $B$ are initiallly aligned.  Frame $B$ is first rotated by  90$^\circ$ around $\hat{Z}$, and then rotated a second time by  45$^\circ$ around the new $\hat{X}_B$ axis.

**1.1**

- Find $^A_B\mathbf{R}$ and sketch frames $A$ and $B$ with respect to
  one another
  
**1.2**

- Repeat 1.1 but reverse the order of rotations: first rotate
  45$^\circ$ about $\hat{X}$ and then rotate 90$^\circ$ about
  $\hat{Z}_B$

### 1.1

In [18]:
thz = 90
thx = 45

In [24]:
Rz = robotics.Rz(thz)
Rx = robotics.Rx(thx)
R_ab = robotics.prettymat(np.dot(Rz,Rx))
R_ab

array([[ 0.        , -0.70710678,  0.70710678],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678,  0.70710678]])

### 1.2

In [25]:
Rz = robotics.Rz(thz1)
Rx = robotics.Rx(thx1)
R_ab = robotics.prettymat(np.dot(Rx,Rz))
R_ab

array([[ 0.        , -1.        ,  0.        ],
       [ 0.70710678,  0.        , -0.70710678],
       [ 0.70710678,  0.        ,  0.70710678]])

<img src="https://drive.google.com/uc?id=1on4UR70ddaLuPY16tu5O2bszmyX2L-ig" width=600px>


## Problem 2

<img src="https://drive.google.com/uc?id=1GbbJ9WfosJAUd6KKH1I6vuodtbuMKLMv" width=450px>

The image above shows a rectangular prism where the top and bottom are isosceles right triangles (45$^\circ$/45$^\circ$/90$^\circ$).

- Find $^A_B\mathbf{T}$, $^B_C\mathbf{T}$, and $^C_A\mathbf{T}$ graphically, using dot products


- Find $^A_C\mathbf{T}$ using any method you choose


- Verify that $^C_A\mathbf{T} = \; ^A_C\mathbf{T}^{-1}$


- Verify that $^A_C\mathbf{T}^T\ \neq \; ^A_C\mathbf{T}^{-1}$

- Find $^A_B\mathbf{T}$, $^B_C\mathbf{T}$, and $^C_A\mathbf{T}$ graphically, using dot products

<img src="https://drive.google.com/uc?id=1Zrs2WgXkN51knwjlvU1NZrgSPEk633oe" width=650px>

- Find $^A_C\mathbf{T}$ using any method you choose

In [37]:
th = 45
Tab = ([cosd(th),-sind(th),0,2.82843],[-sind(th),-cosd(th),0,2.82843],[0,0,-1,1],[0,0,0,1])
Tbc = ([-cosd(th),sind(th),0,4],[-sind(th),-cosd(th),0,0],[0,0,-1,0],[0,0,0,1])
Tac = robotics.prettymat(np.dot(Tab,Tbc),1)
Tac

array([[0.        , 1.        , 0.        , 5.65685712],
       [1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

- Verify that $^C_A\mathbf{T} = \; ^A_C\mathbf{T}^{-1}$

In [42]:
Tca = np.linalg.inv(Tac)
Tca

array([[ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.        , -5.65685712],
       [ 0.        ,  0.        ,  1.        , -1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

- Verify that $^A_C\mathbf{T}^T\ \neq \; ^A_C\mathbf{T}^{-1}$

In [ ]:
Tac_t = np.transpose(Tac)
T