# Homework #3

In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rz, Ry, Rx, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Problem 1

In [14]:
th1 = 60
th2 = 160
th3 = 270

### Case 1

In [15]:
R_ab1 = robotics.Rx(th1)
R_ab1

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.5      , -0.8660254],
       [ 0.       ,  0.8660254,  0.5      ]])

<img src="https://drive.google.com/uc?id=1mp2MWtmruAJd97cO8ZsNGz0HFOPij12t" width=550px>

d. The unit vector components make sense and agree with thr rotation matrix

### Case 2

In [16]:
R_ab2 = robotics.Rx(th2)
R_ab2

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        , -0.93969262, -0.34202014],
       [ 0.        ,  0.34202014, -0.93969262]])

<img src="https://drive.google.com/uc?id=1R9uSkg-8hnGUOKCtMJJOqS_k8MFQvf7F" width=600px>

d. The unit vector components make sense and agree with the rotation matrix

### Case 3

In [17]:
R_ab3 = robotics.prettymat(robotics.Rx(th3))
R_ab3

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0., -1.,  0.]])

<img src="https://drive.google.com/uc?id=1NtsjedT7KMTPstUYhFkxcZbkKQwMeIcd" width=600px>

d. The unit vector components make sense and agree with the rotation matrix

## Problem 2

In [18]:
th2 = 25
Pa = np.array([3,4,0,1])
HT_x = robotics.HTx(-90,0,0,0)
HT_y = robotics.HTy(-(90-th2),0,0,0)
Pb = robotics.prettymat(robotics.dot_list([HT_y,HT_x,Pa]))
Pb

array([4.89308593, 0.        , 1.02845031, 1.        ])

## Problem 3

### 3.1

In [19]:
Rx = robotics.Rx(45)
Rz = robotics.Rz(30)
R_ab = np.dot(Rz,Rx)
R_ab

array([[ 0.8660254 , -0.35355339,  0.35355339],
       [ 0.5       ,  0.61237244, -0.61237244],
       [ 0.        ,  0.70710678,  0.70710678]])

### 3.2 

In [20]:
Rx = robotics.Rx(45)
Rz = robotics.Rz(30)
R_ab = np.dot(Rx,Rz)
R_ab

array([[ 0.8660254 , -0.5       ,  0.        ],
       [ 0.35355339,  0.61237244, -0.70710678],
       [ 0.35355339,  0.61237244,  0.70710678]])

<img src="https://drive.google.com/uc?id=1yz5tdPpa0KJoy8_T-LTy6TezQBQN5B3p" width=700px>