# Class 3 Learning Activities

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

**Note:** In the cell above, `sin`, `cos`, `pi`, ... have been imported from `numpy` so that I don't need to type `np.` before them.

Similarly, `Rx`, `Ry`, `Rz` and so on have been imported from `robotics`.


## Problem 1

Find $^BP$, $^AP$, $^BQ$, and $^AQ$ for the sketch below:

- use rotation matrices and `robotics.py`
- check your signs on all terms conceptually

<img src="https://drive.google.com/uc?id=1HYirryT6yzGG-rEcySIJvLDr4bbO3Bbq" width=400px>

In [6]:
Pb = np.array([5,0,0])
Qb = np.array([0,3,0])

Rp = robotics.Rz(25)
Rq = robotics.Rz(25)

Pa = np.dot(Rp,Pb)
Qa = np.dot(Rp,Qb)
Pa

array([4.53153894, 2.11309131, 0.        ])

In [7]:
Qa

array([-1.26785479,  2.71892336,  0.        ])

## Problem 2

Again, find $^BP$, $^AP$, $^BQ$, and $^AQ$ for the sketch below using rotation matrices and check your signs conceptually.

<img src="https://drive.google.com/uc?id=1GJSgY_-rVS9D22Vq40nbbx3oxNcpKEji" width=350px>

In [10]:
Pb = np.array([3,0,0])
Qb = np.array([0,4,0])

Rp = robotics.Rz(-30)
Rq = robotics.Rz(-30)

Pa = np.dot(Rp,Pb)
Qa = np.dot(Rp,Qb)
Pa

array([ 2.59807621, -1.5       ,  0.        ])

In [11]:
Qa

array([2.        , 3.46410162, 0.        ])

## Problem 3



Find $^BP$ and $^AP$ using rotation matrices.  Again, check your signs conceptually.

<img src="https://drive.google.com/uc?id=12VTxinAIPzNssAk-u_Y0dgUBxz53Wf1Q" width=350px>

In [12]:
Pb = np.array([4,2,0])

R = robotics.Rz(-30)

Pa = np.dot(R,Pb)
Pa

array([ 4.46410162, -0.26794919,  0.        ])

## Problem 4

Derive the rotation matrix for $\mathbf{R}_x(\theta)$.

In [ ]:
pic below

## Problem 5

Find $^A_B\mathbf{R}$ for the sketch below:

<img src="https://drive.google.com/uc?id=1uVitdtqBUMcPCl0fQ9YJ6wHZcSg9xLHF" width=450px>

In [ ]:
pic below

## Problem 6

Find $^A_B\mathbf{R}$ for the sketch below:
- think about how the unit vectors are mapped from frame $B$ to frame $A$

<img src="https://drive.google.com/uc?id=1RPcKLLgUHwNNguivWta-8QGVDbga1Ov9" width=350px>

In [ ]:
pic below

<img src="https://drive.google.com/uc?id=1jzOIQ2wqNu8RSmU8i8pfabdyhismxzhx" width=450px>