In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Problem 1

<img src="https://drive.google.com/uc?id=13xZoRttTU6p11YgV77pmNBWbe6k3LAPP" width=450px>

Find $^BP$, $^BQ$, $^BR$, $^AS$ using HT matrices.

In [16]:
Pa = np.array([0,10,0]) 
Qa = np.array([9,0,0])
Ra = np.array([10,0,0])
Sb = np.array([0,0,3])
Z= np.array([0,0,0,1])
Pborga= np.array([9,10,0])
Rab =  np.array([[0,-sind(20),cosd(20)],
                 [0,-cosd(20),-sind(20)],
                 [1,0,0]])
Rba = np.transpose(Rab)


In [19]:
Tab_temp = np.column_stack([Rba,Pborga])
Tab = np.row_stack((Tab_temp,Z))
Tab
Tba = robotics.HTinv(Tab)
Paorgb = -np.dot(Rba,Pborga)
Pb = Tab *
Qb = 
Rb = 
Sa = 

### Answers:

$$^AS = \; \begin{bmatrix} 11.82 \\ 8.974 \\ 0 \\ 1 \end{bmatrix}

## Problem 2



<img src="https://drive.google.com/uc?id=1EmWSG3rLUpdqbhNxZnu5xjAWzYFRosnB" width=400px>

If $d$ = 10 in, $L$ = 8in, and $\theta=25^\circ$, use HT matrices to find $^0P$.

In [ ]:
P1 = np.array([l,0,0,1])
P0 = np.dot(robotics.HTz(theta,x=d,y=0,z=0),P1)


## Problem 3

Solve the silverbox robot problem using HT matrices:

<img src="https://drive.google.com/uc?id=1cstxZePo6s3XfSzMkWID4E_mdSExTQkm" width=450px>

<img src="https://drive.google.com/uc?id=1AA2dilCYYbOX0XqNmQN_DKpIdfnDsOth" width=450px>

<img src="https://drive.google.com/uc?id=1tk5mwGjYVSzhmAusbePHvIJfpxBLFRb3" width=400px>

Given the parameters below, find the tip position in the global coordinate system using HT matrices.

**Note:** There is a 90$^\circ$ rotation about $\hat{X}_1$ to get from $\hat{Z}_1$ to $\hat{Z}_2$.

In [20]:
L1 = 6
L2 = 6.75
th1 = 20
th2 = 30
th3 = 40

#### Answer to Problem 3:

$$^0P = \; \begin{bmatrix} 7.052 \\ 2.567 \\ 9.343 \end{bmatrix}$$

## Problem 4

Given 

$$^A_B\mathbf{T} = \; \begin{bmatrix} 0 & -1 & 0 & 5 \\ 0 & 0 & -1 & 0 \\ 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

Find $^B_A\mathbf{T}$ without using Python or a calculator.  Check your answer using `robotics.HTinv`.

In [21]:
Tab = np.array([[0,-1,0,5],[0,0,-1,0],[1,0,0,0],[0,0,0,1]])
Tba = robotics.HTinv(Tab)
Tba

array([[ 0.,  0.,  1., -0.],
       [-1.,  0.,  0.,  5.],
       [ 0., -1.,  0., -0.],
       [ 0.,  0.,  0.,  1.]])

## Problem 5

- look at the source for `robotics.dot_list`
    - it uses the `pop` list method to start with the first matrix in the list
    - it then multiplies the matrices from left to right  to find the overall product
        - this is computationally inefficient
- write a new function that multiplies from right to left so that if the last item in the list is a column vector the new function will be faster
- verify that your new function gives the correct answer
- use the `time.time` function from the `time` module to compare the computational time of your new function to `robotics.dot_list`

In [3]:
robotics.dot_list??

In [3]:
th1 = 30+90
th2 = 20
th3 = -15
alph1 = 0
alph2 = 90
alph3 = -90
a1 =0
a2 = 0
a3 = 0
d1 = 0
d2 = 8+10
d3 = 0
T01 = DH(alph1,a1,th1,d1)
T12 = DH(alph2,a2,th2,d2)
T23 = DH(alph3,a3,th3,d3)
T03 = robotics.dot_list([T01,T12,T23])

Ptip3 = ([0,-6,0,1])
Ptip0 = np.dot(T03,Ptip3)
T03, Ptip0

(array([[-2.29692818e-01, -9.58121477e-01,  1.71010072e-01,
          1.55884573e+01],
        [ 9.15477720e-01, -2.72336574e-01, -2.96198133e-01,
          9.00000000e+00],
        [ 3.30366090e-01,  8.85213269e-02,  9.39692621e-01,
          1.10218212e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([21.33718613, 10.63401945, -0.53112796,  1.        ]))