In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Problem 1

<img src="https://drive.google.com/uc?id=19BbGtMN8x1tKJbMF2xsdreq5Rqme3ey9" width=400px>

- find $^A_B\mathbf{T}$ and $^B_A\mathbf{T}$


- find $^AP$ and $^BQ$

In [12]:
R = robotics.Rz(53.13)
Rt = np.transpose(R)
Vector = ([3,4,0])
Vt = np.dot(-Rt,Vector)
Zeroes = ([0,0,0,1])
R1 = np.column_stack((R,Vector))
Tab = np.row_stack((R1,Zeroes))
R2 = np.column_stack((Rt,Vt))
Tba = np.row_stack((R2,Zeroes))
Tab,Tba

(array([[ 0.60000143, -0.79999893,  0.        ,  3.        ],
        [ 0.79999893,  0.60000143,  0.        ,  4.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[ 6.00001429e-01,  7.99998928e-01,  0.00000000e+00,
         -5.00000000e+00],
        [-7.99998928e-01,  6.00001429e-01,  0.00000000e+00,
         -8.93208512e-06],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]))

**Answers:**

$$^AP = \; \begin{bmatrix} 4.8 \\ 6.4 \\ 0 \\ 1 \end{bmatrix}$$

$$^BQ = \; \begin{bmatrix} 0.6 \\ -0.8 \\ 0 \\ 1 \end{bmatrix}$$

## Problem 2

$$^A_B\mathbf{T} = \; \begin{bmatrix} -0.1736 & -0.9848 & 0 & -0.8682 \\ 0.9848 & -0.1736 & 0 & 4.924 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

- sketch the frames $A$ and $B$ in relation to one another

## Problem 3

If you already have 

$$^A_B\mathbf{T} = \; \begin{bmatrix} -0.5 & -0.866 & 0 & 3 \\ 0 & 0 & 1 & 1 \\ -0.866 & 0.5 & 0 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

- use Python to find $^B_A\mathbf{R}$ and $^BP_{AORG}$

In [16]:
T_AB3 = np.array([[-0.5      , -0.8660254,  0.       ,  3.       ],
                 [ 0.       ,  0.       ,  1.       ,  1.       ],
                 [-0.8660254,  0.5      ,  0.       ,  0.       ],
                 [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [17]:
T_AB3

array([[-0.5      , -0.8660254,  0.       ,  3.       ],
       [ 0.       ,  0.       ,  1.       ,  1.       ],
       [-0.8660254,  0.5      ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [24]:
Rab = T_AB3[0:3,0:3]
Rba = Rab.T
aPborg = T_AB3[0:3,3]
bPaorg = np.dot(-Rab.T,aPborg)
Rba, bPaorg

(array([[-0.5      ,  0.       , -0.8660254],
        [-0.8660254,  0.       ,  0.5      ],
        [ 0.       ,  1.       ,  0.       ]]),
 array([ 1.5      ,  2.5980762, -1.       ]))

## Problem 4

- Based on what you learned in Problem 3, write a Python function that takes $^A_B\mathbf{T}$ as its input and returns $^B_A\mathbf{T}$ as its output
- write some tests to verify your function is correct

In [31]:
Tab = np.array([[-0.5      , -0.8660254,  0.       ,  3.       ],
                 [ 0.       ,  0.       ,  1.       ,  1.       ],
                 [-0.8660254,  0.5      ,  0.       ,  0.       ],
                 [ 0.       ,  0.       ,  0.       ,  1.       ]])
Rab = T_AB3[0:3,0:3]
Rba = Rab.T
Z = np.array([0,0,0,1])
aPborg = T_AB3[0:3,3]
bPaorg = -np.dot((Rba,aPborg))
Tba_temp = np.column_stack([Rba,bPaorg])
Tba = np.row_stack((Tba_temp,Z))
Tba

TypeError: dot() missing 1 required positional argument: 'b'

In [33]:
def myHTinv(TAB):
    RAB = TAB[0:3,0:3]
    PBorgA = TAB[0:1,-1]
    RBA = RAB.T
    PAorgB = -np.dot(RBA,PBorgA)
    Temp = np.column_stack([RBA,PAorgB])
    TBA = np.row_stack([Temp,[0,0,0,1]])
    return TBA

## Problem 5

<img src="https://drive.google.com/uc?id=19xH9I-vpIYiuvmFIPba6kt3e3DjRnkg6" width=400px>

- Find $P$, $Q$, and $R$ in both frames using HT matrices

In [ ]:
Tabp = 
Tabr = 
Tabq = 

## Problem 6

<img src="https://drive.google.com/uc?id=1AweBUM8JRP5173hlZeym2l6pvxPKjSch" width=400px>

- Find $P$ and $Q$ in both frames using HT matrices