
# Learning Activity: Dot Products Part 2 and Inferring Properties of Rotation Matrices

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rz, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Dot Products Part 2:

### Problem DP 1:

Given the rotation matrix

$$^A_B\mathbf{R} = \; \begin{bmatrix} 0 & 0 & 1 \\ 1 & 0 & 0 \\ 0 & 1 & 0 \end{bmatrix}$$

sketch the frames $A$ and $B$ in relation to one another.

### Problem DP 2:

Given the rotation matrix

$$^A_B\mathbf{R} = \; \begin{bmatrix} 0 & 0 & 1 \\ -1 & 0 & 0 \\ 0 & -1 & 0 \end{bmatrix}$$

sketch the frames $A$ and $B$ in relation to one another.

## Numeric Investigations into Rotation Matrices:

## What do we mean by the inverse of a matrix?

The inverse of a matrix is a matrix, when multiplied by the original matrix, reults in an identity matrix

## What are matrix inverses used for?

Matrix inverses are used to divide as ther is no way to divide with matrices

## How do I find a matrix inverse numerically using `numpy`?

np.linalg.inv(matrix)

## How do I verify that I have found the inverse of a matrix?

- what does it mean to say one matrix is the inverse of another?

multiplying together will give identity matrix

## Do all matrices have inverses?

- how can I tell if a matrix is invertible or not?

if determinant is 0, matrix has an inverse

## Claim 1:

$$^B_A\mathbf{R}(\theta) = \; ^A_B\mathbf{R}(-\theta)$$

for rotation about a single axes.

- How can we numerically verify this?

## Claim 2:

$$^B_A\mathbf{R}(\theta) = \; ^A_B\mathbf{R}(\theta)^{-1}$$

for any rotation matrix.

- What are we saying mathematically?
- How can we numerically verify this?

## Claim 3:

$$^B_A\mathbf{R}(\theta) = \; ^A_B\mathbf{R}(\theta)^{-1} = \; ^A_B\mathbf{R}(\theta)^{T}$$

for any rotation matrix.

- How can we numerically verify this?
- Can we say anything about this mathematically or symbolically for certain cases?
- Do dot products help us here?
    - If the columns are unit vectors, how does that help us?

# Numeric Examples

- use `robotics.py` to transform vectors between frames A and B using $^A_B\mathbf{R}$ or 
$^B_A\mathbf{R}$ as appropriate

<img src=http://www4.gvsu.edu/KRAUSSRY/445_lectures/lecture_04/Rba_active_learning_trimmed.png width="500">

## Problem Statement

- For the axis shown above, use `robotics.py` to find $^A_B\mathbf{R}$ and $^B_A\mathbf{R}$.
- Then calculate $^A\mathbf{P}$, $^B\mathbf{Q}$, $^A\mathbf{M}$, and $^B\mathbf{N}$.
- Compare two different approaches to finding $^B_A\mathbf{R}$
    1. using $R_z(-\theta)$
    2. $^B_A\mathbf{R} \; = \; ^A_B\mathbf{R}^T$
- verify that $^B_A\mathbf{R} \; = \; ^A_B\mathbf{R}^{-1}$
    - also try $R_x$ and $R_y$ and verify that the transpose of a rotation matrix is also the inverse

In [49]:
Na = np.array([0,6,0])
Qa = np.array([4,0,0])
Mb = np.array([0,3,0])
Pb = np.array([5,0,0])
th = 22

### Option 1

In [67]:
Rab = robotics.Rz(th)
Rba = robotics.Rz(-th)
Rab,Rba

(array([[ 0.92718385, -0.37460659,  0.        ],
        [ 0.37460659,  0.92718385,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 0.92718385,  0.37460659,  0.        ],
        [-0.37460659,  0.92718385,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [57]:
Nb = np.dot(Rba,Na)
Qb = np.dot(Rba,Qa)
Ma = np.dot(Rab,Mb)
Pa = np.dot(Rab,Pb)
Nb, Qb, Ma, Pa

(array([2.24763956, 5.56310313, 0.        ]),
 array([ 3.70873542, -1.49842637,  0.        ]),
 array([-1.12381978,  2.78155156,  0.        ]),
 array([4.63591927, 1.87303297, 0.        ]))

### Option 2

In [69]:
Rab = robotics.Rz(th)
Rba = np.transpose(Rab)
Rab,Rba

(array([[ 0.92718385, -0.37460659,  0.        ],
        [ 0.37460659,  0.92718385,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]),
 array([[ 0.92718385,  0.37460659,  0.        ],
        [-0.37460659,  0.92718385,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [70]:
Nb = np.dot(Rba,Na)
Qb = np.dot(Rba,Qa)
Ma = np.dot(Rab,Mb)
Pa = np.dot(Rab,Pb)
Yb, Qb, Ma, Pa

(array([-2.24763956,  5.56310313,  0.        ]),
 array([ 3.70873542, -1.49842637,  0.        ]),
 array([-1.12381978,  2.78155156,  0.        ]),
 array([4.63591927, 1.87303297, 0.        ]))

### Option 3

In [63]:
Rab = robotics.Rz(th)
Rba = np.linalg.inv(Rab)

In [64]:
Nb = np.dot(Rba,Na)
Qb = np.dot(Rba,Qa)
Ma = np.dot(Rab,Mb)
Pa = np.dot(Rab,Pb)
Yb, Qb, Ma, Pa

(array([-2.24763956,  5.56310313,  0.        ]),
 array([ 3.70873542, -1.49842637,  0.        ]),
 array([-1.12381978,  2.78155156,  0.        ]),
 array([4.63591927, 1.87303297, 0.        ]))