In [5]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH, prettymat
rtd = 180/pi
dtr = pi/180

## Problem 1

Frames 1 and 2 are originally aligned and have the same origin (i.e. they are completely coincident).  Frame 2 is rotated by 90$^\circ$ about $\hat{X}_2$ and then translated 10 cm along $\hat{X}_2$.  Frame 2 is then rotated about the new $\hat{Z}_2$ by 30$^\circ$ and translated by 5 cm along $\hat{Z}_2$.  

### Problem 1 A

- Find $^1_2\mathbf{T}$ using `robotics.HTx`, `robotics.HTz`, and `np.dot`
    - compare this HT matrix to using `robotics.DH`
- sketch frames 1 and 2 with respect to one another

### Problem 1B

- Repeat problem 1 A, but reverse the order of the rotations and translations:
    - translate by 5 cm along $\hat{Z}$ and rotate by 30$^\circ$ about $\hat{Z}$ first and then translate by 10 cm along the new $\hat{X}_2$ and rotate by 90$^\circ$ about the new $\hat{X}_2$

In [9]:
alpha = 90 
a = 10
theta = 30
d = 5

HTx = robotics.HTx(alpha,a)
HTz = robotics.HTz(theta,d)

T12_p2 = prettymat(DH(alpha, a, theta, d))
T12_p1 = prettymat(np.dot(HTx,HTz))
T12_p1, T12_p2

(array([[ 0.8660254, -0.5      ,  0.       , 15.       ],
        [ 0.       ,  0.       , -1.       ,  0.       ],
        [ 0.5      ,  0.8660254,  0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ]]),
 array([[ 0.8660254, -0.5      ,  0.       , 10.       ],
        [ 0.       ,  0.       , -1.       , -5.       ],
        [ 0.5      ,  0.8660254,  0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ]]))

## Problem 2

- Attach the frames necessary to model the robot below using the DH convention
- fill out a table of the DH parameters
- find $^0P_{tip}$ given the values:
    - $L_1$ = 9 cm
    - $L_2$ = 8 cm
    - $L_3$ = 7 cm
    - $\theta_1$ = 20$^\circ$
    - $\theta_2$ = -40$^\circ$
    - $\theta_3$ = 15$^\circ$
    
<img src="https://drive.google.com/uc?id=1-1N0v4UK-UNam_2DuNOHPTA3bQr-vICZ" width=400px>

In [11]:

th1 = 20 
th2 = -40
th3 = 15
alph1 = 0
alph2 = 0
alph3 = 0
a1 =0
a2 = 9
a3 = 8
d1 = 0
d2 = 0
d3 = 0
T01 = DH(alph1,a1,th1,d1)
T12 = DH(alph2,a2,th2,d2)
T23 = DH(alph3,a3,th3,d3)
T03 = robotics.dot_list([T01,T12,T23])

Ptip3 = ([7,0,0,1])
Ptip0 = np.dot(T03,Ptip3)
Ptip0

array([22.94813744, -0.26807006,  0.        ,  1.        ])

## Problem 3

- Attach the frames necessary to model the robot below using the DH convention
- fill out a table of the DH parameters
- find $^0P_{tip}$ given the values:
    - $A$ = 10 cm
    - $B$ = 8 cm
    - $C$ = 6 cm
    - $\theta_1$ = 30$^\circ$
    - $\theta_2$ = 20$^\circ$
    - $\theta_3$ = -15$^\circ$
    
<img src="https://drive.google.com/uc?id=1550T-dKKBKwO93b0nDI0Mnqeibfr94pp" width=450px>

### My Way

In [17]:
th1 = 30 
th2 = 0
th3 = -15
alph1 = 0
alph2 = 20
alph3 = 0
a1 =0
a2 = 10
a3 = 8
d1 = 0
d2 = 0
d3 = 0
T01 = DH(alph1,a1,th1,d1)
T12 = DH(alph2,a2,th2,d2)
T23 = DH(alph3,a3,th3,d3)
T03 = robotics.dot_list([T01,T12,T23])

Ptip3 = ([6,0,0,1])
Ptip0 = np.dot(T03,Ptip3)
T03, Ptip0

(array([[ 0.95812148, -0.22969282,  0.17101007, 15.58845727],
        [ 0.27233657,  0.91547772, -0.29619813,  9.        ],
        [-0.08852133,  0.33036609,  0.93969262,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([21.33718613, 10.63401945, -0.53112796,  1.        ]))

### Your Way

In [19]:
th1 = 30+90
th2 = 20
th3 = -15
alph1 = 0
alph2 = 90
alph3 = -90
a1 =0
a2 = 0
a3 = 0
d1 = 0
d2 = 8+10
d3 = 0
T01 = DH(alph1,a1,th1,d1)
T12 = DH(alph2,a2,th2,d2)
T23 = DH(alph3,a3,th3,d3)
T03 = prettymat(robotics.dot_list([T01,T12,T23]))

Ptip3 = ([0,-6,0,1])
Ptip0 = np.dot(T03,Ptip3)
T03, Ptip0

(array([[-0.22969282, -0.95812148,  0.17101007, 15.58845727],
        [ 0.91547772, -0.27233657, -0.29619813,  9.        ],
        [ 0.33036609,  0.08852133,  0.93969262,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([21.33718613, 10.63401945, -0.53112796,  1.        ]))

## Problem 4 (Example 3.4)

<!-- Slide 2 -->

- draw the schematic
- fill in the DH table
- note the actuated parameters

<img src="https://drive.google.com/uc?id=1K1a58_P9mfsiBbFM1uhLQIhN57CHxsRq" width=400px>


## Problem 5

- draw the schematic and fill in the DH table

<img src="https://drive.google.com/uc?id=1rV1zxDViyq2VkTdFD9G0ONDQII7SCYFw" width=400px>
